# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVMq2e5uYtfob2UyPEhMVR21sJjjM6mU
"""

# install the datasets library
# !pip install datasets  - used to installed dataset

from datasets import load_dataset

dataset = load_dataset("clinc/clinc_oos","plus")
print(dataset)

for i in range(5):
  print("Text:", dataset["train"][i]["text"])
  print("Intent", dataset["train"][i]["intent"])

# This gives us the intent names
intent_names = dataset["train"].features["intent"].names

# Now print with names instead of numbers
for i in range(5):
    text = dataset["train"][i]["text"]
    intent_number = dataset["train"][i]["intent"]
    intent_name = intent_names[intent_number]

    print(f"Text: {text}")
    print(f"Intent: {intent_name}")
    print("---")

# Extract text and labels from dataset
train_texts = dataset["train"]["text"]
train_labels = dataset["train"]["intent"]

test_texts = dataset["test"]["text"]
test_labels = dataset["test"]["intent"]

# Check what we got
print("Total training examples:", len(train_texts))
print("Total test examples:", len(test_texts))
print()
print("Sample text:", train_texts[0])
print("Sample label:", train_labels[0])

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

import nltk
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize
text= "what is my balance"
tokens= word_tokenize(text)
print(tokens)

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))
tokens= [word for word in tokens if word not in stop_words]
print(tokens)

import nltk
nltk.download('wordnet')

def preprocess(text):
    import re
    from nltk.corpus import stopwords
    from nltk.stem import WordNetLemmatizer
    # Step 1 - lowercase
    text = text.lower()

    # Step 2 - remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    # Step 3 - tokenize
    tokens = word_tokenize(text)
    lemmatizer= WordNetLemmatizer()

    # Step 4 - remove stopwords AND lemmatize together
    stop_words= set(stopwords.words("english"))
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    # Step 5 - join back to string
    return ' '.join(tokens)

word_sen= "what is My account balance???"
preprocess(word_sen)

train_texts_clean = [preprocess(text) for text in train_texts]
test_texts_clean = [preprocess(text) for text in test_texts]

print("Before:", train_texts[0])
print("After:", train_texts_clean[0])

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer= TfidfVectorizer(max_features = 50000, ngram_range = (1, 2), sublinear_tf = True)
X_train= vectorizer.fit_transform(train_texts_clean)
X_test= vectorizer.transform(test_texts_clean)
print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

model_lr= LogisticRegression(max_iter=1000, C=1.0)
model_lr.fit(X_train, train_labels)
model_lr.predict(X_test)


model_svc = LinearSVC(max_iter=1000, C=1.0)
model_svc.fit(X_train, train_labels)
model_svc.predict(X_test)

model_nb= MultinomialNB()
model_nb.fit(X_train, train_labels)
model_nb.predict(X_test)

lr_pred  = model_lr.predict(X_test)
svc_pred = model_svc.predict(X_test)
nb_pred  = model_nb.predict(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import ComplementNB

model_lr = LogisticRegression(max_iter=1000, C=1.0)
model_lr.fit(X_train, train_labels)
lr_pred = model_lr.predict(X_test)
print("LR done")

model_svc = LinearSVC(max_iter=1000, C=1.0)
model_svc.fit(X_train, train_labels)
svc_pred = model_svc.predict(X_test)
print("SVC done")

model_nb = ComplementNB()
model_nb.fit(X_train, train_labels)
nb_pred = model_nb.predict(X_test)
print("NB done")

print(lr_pred)
print(svc_pred)
print(nb_pred)

from sklearn.metrics import accuracy_score, classification_report

# Model 1: Logistic Regression
lr_acc = accuracy_score(test_labels, lr_pred)
print("LR Accuracy:", lr_acc)
print(classification_report(test_labels, lr_pred))

# Model 2: SVC
svc_acc = accuracy_score(test_labels, svc_pred)
print("SVC Accuracy:", svc_acc)
print(classification_report(test_labels, svc_pred))

# Model 3: NB
nb_acc = accuracy_score(test_labels, nb_pred)
print("NB Accuracy:", nb_acc)
print(classification_report(test_labels, nb_pred))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

fig, axes = plt.subplots(1, 3, figsize=(20, 6))
models = [
    ("Logistic Regression", lr_pred),
    ("SVC", svc_pred),
    ("Naive Bayes", nb_pred)
]

for ax, (name, pred) in zip(axes, models):
  cm = confusion_matrix(test_labels, pred)
  disp = ConfusionMatrixDisplay(cm)
  disp.plot(ax=ax, colorbar=False)
  ax.set_title(name)


plt.suptitle("Confusion Matrix Comparison", fontsize=16)
plt.tight_layout()
plt.savefig("confusion_matrices.png")
plt.show()

import numpy as np
train_labels_array = np.array(train_labels)

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

param_grid = {
    'C': [0.1, 1, 10],
    'solver': ['lbfgs', 'saga'],
    'max_iter': [100, 200]
}

grid = GridSearchCV(LogisticRegression(), param_grid, cv=3, n_jobs=-1, verbose=1)
grid.fit(X_train, train_labels_array)

print("Best Params:", grid.best_params_)
print("Best Score:", grid.best_score_)

import joblib
best_model = grid.best_estimator_
joblib.dump(best_model, 'best_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')
print("Model saved!")

from google.colab import files
files.download('best_model.pkl')
files.download('vectorizer.pkl')

# Check what out-of-scope label looks like
print(dataset["train"]["intent"][0])
print(set(dataset["train"]["intent"]))

from datasets import load_dataset
ds = load_dataset("clinc/clinc_oos", "plus")
print(ds['train'].features['intent'].names.index('oos'))